Bump deps
stylelint/stylelint-checkstyle-formatter pull request #8
Opened 2018-08-08 08:35 UTC by crudo

Bump Lodash because of https://www.npmjs.com/advisories/577

2018-08-08 10:28 UTC, MhMadHamster requested changes

2018-08-08 10:28 UTC, MhMadHamster commented on package.json
> +    "lodash": "4.17.10"
can we not specify the exact version for dependencies and devDependencies?

2018-08-08 12:15 UTC, crudo commented
I personally consider using tilde or caret as a bad practise, but as you wish :)

2018-08-08 12:48 UTC, MhMadHamster approved these changes

2018-08-08 12:48 UTC, merged

2018-09-04 06:49 UTC, crudo commented
@MhMadHamster Would you please release new version?

2018-09-05 11:10 UTC, MhMadHamster commented
done